### ISSUE TITLE
Internal vs Public ip's and hosts

### ISSUE THREAD

**Issue by ghukill** [MI-DPLA/combine#334]
A build on AWS revealed that some network calls to local services -- e.g. ElasticSearch, Livy -- are using the public IP of the Combine machine.  A public IP is needed (convenient) if those ports and services should be reachable, but no need for local calls to hit IP.  Will be faster avoiding loopback, as well.

Consider adding `PUBLIC` and `INTERNAL` prefixes to these settings in `localsettings.py` to differentiate, then confirm the appropriate ones are used in Combine.

**Comment by ghukill** [comment]
Possible overlap with #310?

**Comment by ghukill** [comment]
Releated #310

**Comment by estelendur** [comment]
Fixed in [docker deployment](https://github.com/MI-DPLA/combine-docker)
