### ISSUE TITLE
job management: include upstream Jobs?

### ISSUE THREAD

**Issue by ghukill** [MI-DPLA/combine#358]
Encoutered a situation where it would be handy to select the *single* Merge Job and re-run, but also trigger the re-harvesting of the 40-50 OAI Harvests that are *input* Jobs to this Job.

Currently, would be required to select all 40-50 OAI Harvests and re-run, which would trigger the re-merge last.

**Comment by estelendur** [comment]
How closely related is this to https://github.com/MI-DPLA/combine/issues/410?

**Comment by ghukill** [comment]
Tangential, I think.  The thinking here was the ability to re-run all "upstream" jobs from Job `foo`.  This would include the input jobs that flowed into Job `foo`, their input jobs, and recursively "upstream".  

Currently all re-running all *downstream* jobs from Job `foo` is an option, but the functionality had not been included to re-run all upstream.

Re-running Jobs at Org or Record Group level might achieve similar goals, but this was from the POV of a single Job.
