### ISSUE TITLE
add restart Django manage.py management command

### ISSUE THREAD

**Issue by ghukill** [MI-DPLA/combine#369]
Would be a subset of `update` - perhaps, they should work in tandem?

**Comment by estelendur** [comment]
Can you expand on the context for this? @ghukill

**Comment by ghukill** [comment]
Idea was a Django management command that would restart Django app, Celery, and Livy (and possibility refresh session).  Currently these actions happen when `python manage.py update` is run, but they are a bit piecemeal.

The Docker deployment has added a bit of complexity to this as the Django app, Celery, and Livy are all in separate containers, and thus can't readily be restarted from the context of a Django management command.

However, probably would still have utility in a non-Docker environment.

**Comment by estelendur** [comment]
Not useful to any actual users we are aware of.
