### ISSUE TITLE
refactor models.py

### ISSUE THREAD

**Issue by ghukill** [MI-DPLA/combine#377]
Per an extremely helpful discussion, it was recommended that refactoring `models.py` to multiple smaller files might help with file management, navigation, etc.  

Proposing a structure along the lines of:

```
models/
   __init__.py <------ will import classes from sibling .py files
   job.py
   record.py
   combinejob.py
   etc.
```

It might make sense to combine some classes into the same file, where they have interelated functionality (like interacting with s3).  Or Livy session management.  But certainly some of the larger classes like `Job` and `Record` and `CombineJob` might benefit from their own dedicated file.

An alternative would be breaking up Combine's main Django app `core` into more Django applications.

**Comment by estelendur** [comment]
I think this is sufficiently done to be closed, and further major improvements might warrant their own issue.

**Comment by ghukill** [comment]
Agreed.  Thanks, and closing.
