### ISSUE TITLE
consider https for Combine Django app

### ISSUE THREAD

**Issue by ghukill** [MI-DPLA/combine#386]
pointed out that Combine runs almost entirely on `http`, but hopefully would not be terribly difficult to move Django app to optional `https` as well

**Comment by estelendur** [comment]
We may actually be able to do this just by configuring nginx properly. Which is good, since we aren't in direct control of most deployments and you do need a valid certificate to run https. But I can write up a how-to and link to Let's Encrypt, probably.

**Comment by richardcadler** [comment]
nginx can do this for us. Just waiting on an SSL certificate. @estelendur

**Comment by estelendur** [comment]
Fixed in [docker deployment](https://github.com/MI-DPLA/combine-docker)
