### ISSUE TITLE
Re-Run all Jobs at Organization and Record Group level

### ISSUE THREAD

**Issue by ghukill** [MI-DPLA/combine#410]
During a helpful discussion with @richardcadler, it was suggested that there might be utility in the ability to re-run Jobs at the Organization and Record Group level.

Imagine the Org / Record Group structure:

```
University of Jupiter (org)
    - Europa (record group)
        - single harvest job published as "europa"
    - Ganymede (record group)
        - multiple harvests, transforms, and a final merge, published as "ganymede"
    - Io (record group)
        - multiple harvests and transform, published as "io"
```

When it is desired that all published records in Combine be refreshed from their sources -- at this point, three jobs -- it would require clicking into each Record Group and re-running the appropriate jobs.  This would be more cumbersome at 10,20,50 Record Groups, all with unknown arrangements of Jobs inside.

But, functionality could be added that allowed re-running all Jobs of an Organization or Record Group that would trigger this.  

**Consideration**: this would trigger *all* Jobs, perhaps even those not relevant or published.  Could add flag that only sniff out published Jobs, and only rerun their lineage.  Or just leave to happen (easier).

This moves a step closer to **scheduling** the re-running of Jobs, most often, likely OAI harvests that are liable to change based on updated records in their respective OAI sources.

**Comment by estelendur** [comment]
Clarification/summary from @ghukill over Slack:
> Stop/Re-Run buttons at 1) All Organizations page (viewing table of multiple Orgs), 2) Single Organization page (viewing table of multiple RGs)

**Comment by estelendur** [comment]
Do these screenshots seem like basically the desired UI? @richardcadler 
![image](https://user-images.githubusercontent.com/10409866/59378334-18716580-8d22-11e9-95c3-614fa4e0e037.png)
![image](https://user-images.githubusercontent.com/10409866/59378364-28894500-8d22-11e9-97f8-83dcc46d42ad.png)

**Comment by ghukill** [comment]
This looks awesome!  Exactly what had been proposed.
