### ISSUE TITLE
Release 0.10

### ISSUE THREAD

**Issue by estelendur** [MI-DPLA/combine#449]
Need to get a staging server up and running. Need to work through a full workflow on the staging server. Need to fix any bugs discovered.

**Comment by estelendur** [comment]
The current blocker is that when the staging server is up and running, livy doesn't respond to any attempts at contact. Working on this with ops.

**Comment by estelendur** [comment]
Livy was having an issue with conflicting jar files for jetty. It's possible that fixing that fixes the issue. I tried to deploy to a fresh ubuntu VM from scratch and have been running into all sorts of other problems. There's a python3/python2 issue...

**Comment by estelendur** [comment]
Okay! I think I have a working staging deployment!

**Comment by ghukill** [comment]
Ah-ha!  Good find.
