### ISSUE TITLE
Add a more accurate message to the "Is Valid" field when a job did not include validation

### ISSUE THREAD

**Issue by richardcadler** [MI-DPLA/combine#457]
Currently a job shows 'True' when all records have validated, which is good. But it also shows 'True' if there were >0 records in the job but validation was skipped. This could lead to confusion about the (un)validated status of records in that job.

So in the latter case it would be better to have the field display something like "Undetermined" or "Validation not run."  (But not "unvalidated" because that might imply there's a validation problem when that's actually not been determined yet.)

**Comment by estelendur** [comment]
I believe this is actually fixed in dev/on staging.

![image](https://user-images.githubusercontent.com/10409866/73098918-605f8a00-3eb8-11ea-8aae-e4678498d122.png)
