### ISSUE TITLE
CRUDs for Validation Scenarios, Transformations, and OAI endpoints

### ISSUE THREAD

**Issue by ghukill** [MI-DPLA/combine#87]
Currently, none of these have a graphical CRUD in Combine, all have been entered through Django admin screen.

  * Validation Scenario
    * there is a screen to test validations, this could be merged with a CRUD to create
  * Transformations
    * might be helpful to have a CRUD that allows for previewing a transformation before adding (could be similar interface to validation screen)
  * OAI endpoints
    * might be helpful to allow pinging the OAI endpoint and retrieving sets, etc.

**Comment by estelendur** [comment]
We've got basic CRUD interfaces for nearly all the configuration models (except DPLABulkDataDownload?). I see several other tickets hiding in the text of this issue, though.

**Comment by ghukill** [comment]
Agreed.  And `DPLABulkDataDownload` will need separate attention, as it's become stale with changing DPLA data (or at least, variance between ingestion versions).

Feel as though it'd be safe to close this, with an eye towards new issues where applicable.
